print("*data collection")
print("")
print(f"1. Water fountains: ")
water_fountains = int(input("enter the number of water fountains: "))
location_water_fountains = (input("enter the locations of these water fountains: "))
water_condition = input("input the condition of these water fountains: ")
print("")
print("")
print(f"2. Restrooms")
restrooms = int(input("enter the number of restrooms: "))
location_restrooms = input("enter the locations of these restrooms: ")
restroom_condition = input("input the cleanliness of these restrooms: ")
print("")
print("")
print(f"3. Classrooms: ")
classrooms = int(input("enter the number of classrooms: "))

water_per_class = water_fountains / classrooms
restrooms_per_class = restrooms / classrooms

print("")
print("")
print("*data collected")
print("")
print(f"1. Water Fountains: ")
print(f"locations: {location_water_fountains}")
print(f"condition: {water_condition}")
print("")
print(f"2. Restrooms:")
print(f"number of restrooms: {restrooms}")
print(f"location: {location_restrooms}")
print(f"cleanliness: {restroom_condition}")
print("")
print(f"3. Classrooms: ")
print(f"total number of classrooms: {classrooms}")
print(f"number of water fountains per classroom: {water_per_class}")
print()


